# Change these first
owner: y9yk # Your GitHub organization or username, where this repository lives
repo: api-upp # The name of this repository

sites:
  - name: Google
    url: https://www.google.com
  - name: Wikipedia
    url: https://en.wikipedia.org
  - name: Hacker News
    url: https://news.ycombinator.com
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co

status-website:
  # cname: api-status.bereview.co.kr
  baseUrl: /api-upp
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: BEREVIEW API Uptime
  introTitle: "BEREVIEW API Uptime"
  introMessage: 빌리뷰에서 제공하는 서비스 API들의 uptime 상황을 보여드립니다.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO